spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expengine?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    data-username: root
    data-password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
mybatis:
  type-aliases-package: com.gang.expengine.core.dao.entity
  mapper-locations: classpath:mapper/*.xml

