
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${datebase.url}
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true
    sql-script-encoding: UTF-8
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      jdbc-url: jdbc:mysql://127.0.0.1:3306/engine?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowMultiQueries=true
      username: root
      password: 123456
      allow-pool-suspension: true
      auto-commit: true
      idle-timeout: 300000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 300000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    database: 6
  cache:
    redis:
      time-to-live: 86400000
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    joda-date-time-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    default-property-inclusion: non-null
    parser:
      allow-missing-values: true
      allow-backslash-escaping-any-character: true
      allow-unquoted-field-names: true
      allow-unquoted-control-chars: true
    serialization:
      write-null-map-values: false
      order-map-entries-by-keys: false
      write-single-elem-arrays-unwrapped: false
      eager-serializer-fetch: true
#mybatis:
#  mapper-locations: classpath*:/mybatis-mapper/*.xml
#  config-location: classpath:/mybatis/mybatis-config.xml
logging:
  level:
    root: info
    com.netflix.discovery: error
    org.springframework.cloud.openfeign: trace
    com.netflix.config.ChainedDynamicProperty: trace
    feign.Client.Default: trace
server:
  port: 8666